### ISSUE TITLE
Create individual mutual fund page

### ISSUE THREAD

**Issue by StevenGerdes** [edegraff/FundTracker#1]

**Comment by StevenGerdes** [comment]
I'm thinking it will be a graph displaying a good amount of data which can be scaled. A table which will show the average profit for 1 month, 6 months, 1 year, 2 years, 5 years, and 10 years (as they do on their site I think but we will use our data... except we won't have that data).

**Comment by LindsayL** [comment]
I will start by essentially displaying the same data as you would get from a report where you only select the one fund.

**Comment by StevenGerdes** [comment]
Yeah that is essentially all it is isn't it?

**Comment by LindsayL** [comment]
Yeah, for the most part, I guess so.  There was the suggestion you made in the previous comment.  But yeah, I guess that is pretty much it.  

So I was thinking to show all data for a fund, up to a point, like theoretically when there is more than say 1 month of data I will only show the last month.  What do you think?  We could add a show more button, or perhaps just link to reporting "for more detailed information"....

**Comment by StevenGerdes** [comment]
Yeah you know thinking on it we probably should have combined "funds" and "reporting". I guess we don't want to make more work though. But just hypothetically think of the "funds" page being the exact same but with check boxes along the side. If you select one it goes to the page for that single fund and if you select multiple it does the same as selecting them on the reports page. Each page could have the table, the 3 month, 6month, 1 year table etc. and finally instead of having the person preselect the start end date we provide a slider on the page which scales all the data and the graph. 

But if were not going to do that then I guess just link to reporting.

**Comment by LindsayL** [comment]
Each individual fund now gets a mini report for its details page.  A graph, export, and table.

Will add link to reporting for more detail.  (If time permits mayb we can add the slider.)

want to do some styling for the prediction portions of each data.  To come soon. :D

**Comment by LindsayL** [comment]
(Sorry I didn't see that you had already implemented the % table before my last commit)

But everything is in now except the slider so I'm going to close this.

Close with f3c261c7fc970d22c00744737e7225230a30f2a5
