### ISSUE TITLE
Will FundHistory always be sorted from earliest date to most recent?

### ISSUE THREAD

**Issue by LindsayL** [edegraff/FundTracker#16]
I have a function that depends on this (FundEntity.CurrentValue also does).  Just wondering if I should be sorting before.  (And if I should, should I be storing it back to the db to speed up future sorts?)

**Comment by StevenGerdes** [comment]
It won't be sorted automatically and I didn't realize I missed that for FundEntity.CurrentValue. According to this http://stackoverflow.com/questions/9938956/entity-framework-loading-child-collection-with-sort-order it isn't possible to sort it nicely at the database but I guess we should

**Comment by edegraff** [comment]
Won't it always be sorted by date?  Newer values are appended to the end of the FundHistory array.

**Comment by LindsayL** [comment]
I kind of think that might be the case, especially since our functions have been working as expected despite any explicit sorting.  But just in case, I've added a line to sort the data before retrieving a value.  

(Since the data is probably already in order, the sort should be fast.  If it does cause a significant decrease in performance, we could gamble on removing it, but I doubt it will make much difference since we will have very limited data for the project.)
