### ISSUE TITLE
Notifications in website

### ISSUE THREAD

**Issue by StevenGerdes** [edegraff/FundTracker#17]
Currently the notification part of the website is just the auto generated views. These should work to create things to test issue #12 but are in no way done.

**Comment by StevenGerdes** [comment]
I realize that this needs to be done while the stuff left on profile/transaction issue are extra features. I will close issue #18 and then make an issue for each one with a label of optional enhancement. Since you have not assigned your self Evan I assume this is still up for grabs. I will complete it today.

**Comment by edegraff** [comment]
Are you still working on this Steven?

**Comment by StevenGerdes** [comment]
Um you can take it from here if you want

**Comment by StevenGerdes** [comment]
Create works now but no I sadly didn't finish yesterday but as of right now nothing is "unsubmitted". I was going to start again on it once I got home in like an hour or so.

**Comment by StevenGerdes** [comment]
So please assign yourself if you want to take it or leave it if you dont

**Comment by edegraff** [comment]
0ea5b56
 f73fcb3
