### ISSUE TITLE
Protfolio/UserTransaction Pages

### ISSUE THREAD

**Issue by StevenGerdes** [edegraff/FundTracker#18]
(I'm just writing my ideas down so I don't forget them)

Index page
- Paging on transaction history
- Total Assets at bottom of table
- Interactive graph
  - Graph would show an aggregate value line, and a line for each fund that has ever been purchased
  - When hovering over a relevant transaction in the history table highlight point on graph
  - When hovering over a relevant aggregate highlight whole line

Create page
- initialize date to today's date.

Edit Page - remove
View page - remove
Delete Page - remove or at least make it not a page but simply delete from history

**Comment by StevenGerdes** [comment]
Possibly in the aggregate view put change in last week or something like that.

**Comment by LindsayL** [comment]
I really like the way the transaction pages are looking (especially the Current Assest, nice touch)!

I'm sure you've already noticed, but I just created an account and went to the transactions page, I can see all the transactions you've made.

**Comment by StevenGerdes** [comment]
I didn't know that, thanks

**Comment by LindsayL** [comment]
I was looking at the Date box you have in the Create transaction page, it looks exactly like mine I think.  Both have the blue highlighting around when you click on them, but it's not the same as the 2 other boxes you have on Create.  (It also doesn't extend the length of the screen.)  I am testing in chrome.

How/where are you actually applying jqueryui datepicker to the date box?  I had to do this:

$(function() {
      $('input[name="start"]').datepicker();
      $('input[name="end"]').datepicker();
  });

but I don't see similar code for the Create transaction page... (I don't get it :o)

I guess the css for jqueryui is probably interfering with the default styling.

**Comment by StevenGerdes** [comment]
Um so it didn't look the same when I Las commited. I might not have synced. To make a template like date you mist put the file in view/shared/editor templates. I'm doing an errand right now I might be able to explain better later

**Comment by LindsayL** [comment]
Okay, sure thing. :)

**Comment by LindsayL** [comment]
My bad, I didn't do an update.  The date box looks the same now!

**Comment by StevenGerdes** [comment]
All that is in the requirements are done. I will close this and make the existing functionality into its own optional issues

close with 11bc77095b946862dc611f7af9ae8ae0cc21f55f
