### ISSUE TITLE
Reporting slow-ish (Low priority)

### ISSUE THREAD

**Issue by LindsayL** [edegraff/FundTracker#19]
When generating reports it's kind of slow.  Likely because for each fund on each day we do a get value.  This might be improvable through a refactor which grabs all values for the date range for a fund in one request.

**Comment by StevenGerdes** [comment]
Hmm currently it takes forever to do years. I quickly looked at it and it seems like you just get by date for each day? Why not just plot each point? Or plot a defined default number of points between two dates and average the missing numbers. I realize we don't have any data the legitimately goes back 10 years but I thought we could have one fund full of fake data which could be used as an example of long term information.

**Comment by LindsayL** [comment]
I re-did the way reporting gathers the data, it should be faster now.

Close with 689125c39f24d4d3020de2e50df1615b64085c94
