### ISSUE TITLE
Delete/edit a user transation

### ISSUE THREAD

**Issue by StevenGerdes** [edegraff/FundTracker#20]
Normally you wouldn't want to allow a user to delete/edit a user transaction but since they put it in manual they might mess up the input. So I guess we should keep delete and edit? Any thoughts?

**Comment by edegraff** [comment]
Allowing delete seems reasonable, I can't think of a reason a user would want to edit.

**Comment by LindsayL** [comment]
Definitely keep delete.  If edit already works I think we might as well keep it.  If you entered 2/3 things correctly and just wanted to change one it would be significantly faster to edit than to delete and create a new transaction.  But, if it's a lot of work to have/keep edit it's really not that important I don't think.

**Comment by StevenGerdes** [comment]
Well edit exits and works so I will leave it
