### ISSUE TITLE
Add graph to portfolio page

### ISSUE THREAD

**Issue by StevenGerdes** [edegraff/FundTracker#22]
Graph would show an aggregate value line, and a line for each fund that has ever been purchased

I still want to do this but I am waiting on either Lindsay to be done making the graphs reusable or to stop working on it so I can give it a go.

**Comment by LindsayL** [comment]
So I made the graph somewhat reusable.  It is now in the form of a partial that accepts a report model and will graph based on the values from there.  You should also specify whether or not you want the graph options by setting ViewBag.GraphOptions.  The options are the show by value/change buttons at the top of the report.  If you specify false it will just graph the values exactly as shown.

I guess for you to use it in the implementation you want, you would have to create your own report object instantiater with a different signature.

Is what I am using
public Report(DateTime start, DateTime end, List<FundEntity> funds)

I suppose you could make one like:
public Report(DateTime start, DateTime end, List<UserTransaction> trans)

There are two properties required in a report object:

Headers -> literally the headers/column titles for your data.  "Date" should be the first header (to work with the partial), the following would be something like "Aggregate", "Fund1", "Fund 2", etc

Data -> an array of lists of strings.  The first list of strings should be the dates (they should be in the format provided by formatDate(DateTime date)).  The following list of strings should be the values for the corresponding to those dates and the remaining column headers.  So the second list of strings given my example would be the values for "Aggregate" and they should be in the list in the same order as the dates.

With the data in this format the _GraphPartial will take care of the remaining work.  (You can also pass this model into the _ExportPartial and _TablePartial for those components as well.)

If you want I can probably make this report object instantiater.  Just let me know. :)

**Comment by StevenGerdes** [comment]
Actually what I might just do is make my aggregateFundValue implement an interface that is similar to FundEntity. Then I can simply make the report take a list of IFundEntity (essentially might have different name). And thats all that needs to be done

**Comment by LindsayL** [comment]
That sounds quite a bit cleaner!  Sounds good. :)
