### ISSUE TITLE
Other ideas in case we want to add more work for some reason. 

### ISSUE THREAD

**Issue by StevenGerdes** [edegraff/FundTracker#24]
1. Help pages/tool tips
   - I was thinking that maybe the main page could have more detail on how our thing works.  We could have screen shots. It could talk about our prediction algorithm. Also currently when a visitor selects portfolio or notifications it simply prompts to log in. Instead it could have a link to the login page and a description of what they would get for either page.
2. Color!
   - Even though I do like the bootstrap UI design we could pick a color scheme and use it for our site.

**Comment by LindsayL** [comment]
I agree with all these ideas!

I can't remember for sure, but when you are going to notifications/portfolio and are redirected to the login page, after you log in, are you re-directed back to either notifications/portfolio page?  Or back to the home page?
If it is to the home page, it would be nice if it went to where the user was trying to go. :)

**Comment by StevenGerdes** [comment]
It is supposed to go where the user was trying to go. From my small amount of tests it works but for some reason I do remember it failing once but maybe it got fixed or I'm remembering wrong.

**Comment by LindsayL** [comment]
Validation on transactions, when you try to select a date that is earlier than available data it doesn't tell you how far data goes back, so you have to keep guessing.

**Comment by edegraff** [comment]
Color is added! f61a2a22
