### ISSUE TITLE
Database not in sync with model

### ISSUE THREAD

**Issue by LindsayL** [edegraff/FundTracker#6]
Additional information: The model backing the 'DatabaseContext' context has changed since the database was created. Consider using Code First Migrations to update the database (http://go.microsoft.com/fwlink/?LinkId=238269).

**Comment by StevenGerdes** [comment]
Hmm I dont recall submitting anything.

**Comment by LindsayL** [comment]
I think it might be because of adding the new models in DatabaseContext.  Maybe...  (I haven't changed anything regarding the models or database).

```
    public System.Data.Entity.DbSet<Common.Models.Notification> Notifications { get; set; }

    public System.Data.Entity.DbSet<Common.Models.UserTransaction> UserTransactions { get; set; }
```

So I've tried to get the database to migrate, but it ends up failing.

First I made 2 changes:

1) Added:

```
    // Recreates our databases each time a model changes
    Database.SetInitializer<Common.Models.DatabaseContext>(new System.Data.Entity.DropCreateDatabaseIfModelChanges<Common.Models.DatabaseContext>());
```

To FundPortfolio/Global.asax.cs at the beginning of Application_Start().

2) Allowed automiatic migrations in Common/Migrations/Configuration.cs

```
    AutomaticMigrationsEnabled = true;
```

So then next time I attempt to use the database I think it tries to migrate but, it fails with:

```
    An exception of type 'System.Data.SqlClient.SqlException' occurred in EntityFramework.dll but was not handled in user code

    Additional information: There is already an object named 'FundEntity' in the database.
```

Though it does seem to wipe the tables and create new ones...

**Comment by LindsayL** [comment]
Sometimes it also fails with a time out error.  I'm having difficulty figuring out why it's trying to create a second FundEntity table.  

Is it working for you?  I receive these errors while trying to search.

**Comment by StevenGerdes** [comment]
I wasn't at home. Now that I am I fixed it. I just simply did a blank migration. I'm not sure what happened

**Comment by LindsayL** [comment]
Sweet thanks!  (Btw, how do you do that?)

**Comment by StevenGerdes** [comment]
I will make a migrations note on the readme just so it is always there

**Comment by StevenGerdes** [comment]
Also please test on your side after a pull and close this issue if it is fixed. It sure seems fixed on my side

**Comment by LindsayL** [comment]
Yes it is fixed now.  Thanks for the note too!

Close with 6409e8cab9f54b00b732b5465ad6698fd4ec6489
