### ISSUE TITLE
Select Graphing tool

### ISSUE THREAD

**Issue by LindsayL** [edegraff/FundTracker#8]

**Comment by StevenGerdes** [comment]
I have looked at a few and there are two I like. They are both based off of d3.js but d3 is more abstract than we need. 
c3 charts: http://c3js.org/gettingstarted.html
which has a simple interface and decent documentation
dc charts:
The sheer amount of data it can handle is insane. It also can zoom into the data which is super awesome. Drawbacks are much more verbose in terms of creating it and not as nice documentation
http://dc-js.github.io/dc.js/

**Comment by LindsayL** [comment]
Alright, I'm going to try implementing c3 charts for the report page.

**Comment by LindsayL** [comment]
Just finished implementing graphs in reports, c3 was pretty slick.  It was easy to use and the results look pretty good I think.

Close with 69fab8ea3cfea19e20c55f7826f34c153f03410e
