### ISSUE TITLE
Select Prediction Algorithm

### ISSUE THREAD

**Issue by LindsayL** [edegraff/FundTracker#9]

**Comment by LindsayL** [comment]
Here is some information and links I have found.  Largely, it goes from most complex to least.

http://perso.uclouvain.be/michel.verleysen/papers/ffm07sd.pdf

The Gaussian random walk paradigm - under the form of the diffusion geometric
Wiener process - is the core of modelling of financial time series.
Further in this paper, we first describe how Functional Analysis can be applied to
time series data (section 2), and briefly introduce the Radial-Basis Functions Networks
we use as nonlinear models (section 3). Then, we describe the forecasting method itself
(section 4), and illustrate its results on the IBM series of "tick data" (section 5).

http://www.ipredict.it/ForecastingMethods.aspx

Holt's Double Exponential
Holt's Double Exponential is similar to the Double Exponential Moving Average. It allows you to specify the two smoothing constants used in the process. It is useful for data in a simple linear trend.

Holt Winter's Modified Multiple Seasonalities
The Modified Multiple Seasonalities is a proprietary algorithm based on Holt Winter's algorithm that can take into consideration multiple seasonalities. This model is especially suited for financial time series. Two versions of this algorithm are now available with different computational logic.
 (maybe if we had more data)

Linear Trend And Multiple Seasonalities
The Linear Trend and Multiple Seasonalities assume the data is made of a linear trend plus multiple additive or multiplicative seasonalities. It then fits the equation to the data using a Bayesian fit and projects forward in time. It is especially useful for financial time series.

https://msdn.microsoft.com/en-us/library/ms174923.aspx
Microsoft Time Series Algorithm
"Use only ARTXP for short-term prediction."

http://research.microsoft.com/en-us/um/people/dmax/publications/dmart-final.pdf
ARTXP Implementation

https://www.otexts.org/fpp/2/3
2.3 Some simple forecasting methods

Average method
Here, the forecasts of all future values are equal to the mean of the historical data. If we let the historical data be denoted by y1,…,yT, then we can write the forecasts as
y^T+h|T=y¯=(y1+⋯+yT)/T.
The notation y^T+h|T is a short-hand for the estimate of yT+h based on the data y1,…,yT.

Drift method
A variation on the naïve method is to allow the forecasts to increase or decrease over time, where the amount of change over time (called the drift) is set to be the average change seen in the historical data. So the forecast for time n+h is given by
yT+hT−1∑t=2n(yt−yt−1)=yn+h(yT−y1T−1).
This is equivalent to drawing a line between the first and last observation, and extrapolating it into the future.

Inflation adjustments
Data that are affected by the value of money are best adjusted before modelling. For example, data on the average cost of a new house will have increased over the last few decades due to inflation. A $200,000 house this year is not the same as a $200,000 house twenty years ago. For this reason, financial time series are usually adjusted so all values are stated in dollar values from a particular year. For example, the house price data may be stated in year 2000 dollars.
To make these adjustments a price index is used. If zt denotes the price index and yt denotes the original house price in year t , then xt=yt/zt∗z2000 gives the adjusted house price at year 2000 dollar values. Price indexes are often constructed by government agencies. For consumer goods, a common price index is the Consumer Price Index (or CPI).

**Comment by LindsayL** [comment]
Personally, I like the Drift Method.  (Because the others seem quite involved [except average method].)   

And if we wanted to add some additional complexity we could maybe add the inflation adjustments.

But maybe we could do the ARTXP one, the article does seem fairly in depth, we may be able to implement it with that.

**Comment by LindsayL** [comment]
Oooh, or do you think we can make up our own? ;o

like combine the average and drift one.  Take the average, and the most recent point, then extrapolate a line from them.  Hmm, I might test it out, see what kind of accuracy we get. :D

**Comment by LindsayL** [comment]
I'm going to read through the ARTXP method and see how feasible it actually looks.  If it isn't too bad I'll implement it.

**Comment by LindsayL** [comment]
So reading the ARTXP document....  I'm pretty sure I would need to take a course before I could completely understand what it's talking about and be confident in my implementation.  So I'm not sure I can do it. :/

But here are my results from simulating 3 of the simple prediction algorithms.  (Average, Drift, a combination of Average and Drift, and Average(Average, Drift)).  The recorded prediction values are just the prediction value for the very next day.  If we were to predict more than one day in the future the prediction (for all 3) would just continue along the line from the last real point to the first predicted point.

Here is all the Data:

Actual Data
![image](https://cloud.githubusercontent.com/assets/5545461/6857726/7e691ade-d3ce-11e4-967c-27557de14566.png)

Average Drift Combination Predictions
![image](https://cloud.githubusercontent.com/assets/5545461/6857742/926e383e-d3ce-11e4-88f3-e5bc90a38caa.png)

Average
![image](https://cloud.githubusercontent.com/assets/5545461/6857745/9a2ec8fe-d3ce-11e4-8283-c85baf802215.png)

Drift
![image](https://cloud.githubusercontent.com/assets/5545461/6857751/a3d41882-d3ce-11e4-91a3-cfaa56e12121.png)

Average(Average, Drift)
Just the average between the drift and average prediction for the day.

Average(Average, Average Drift Combination)
Just the average between the avg drift combo and average prediction for the day.

I also selected 3 random funds to graph the results:

1)
![image](https://cloud.githubusercontent.com/assets/5545461/6858296/fb877b92-d3d2-11e4-858d-b8d7ce810494.png)

![image](https://cloud.githubusercontent.com/assets/5545461/6858306/10bd1648-d3d3-11e4-9b1e-26930eab39bb.png)

How much each method was off by
![image](https://cloud.githubusercontent.com/assets/5545461/6858311/1baf971a-d3d3-11e4-87d9-f846b30f182e.png)

![image](https://cloud.githubusercontent.com/assets/5545461/6858313/1fe311fe-d3d3-11e4-99be-e494385d8ec5.png)

2)
![image](https://cloud.githubusercontent.com/assets/5545461/6858319/2bb0972c-d3d3-11e4-9d7b-db506dbd7349.png)

![image](https://cloud.githubusercontent.com/assets/5545461/6858321/2e18b7e2-d3d3-11e4-8ec1-38b067b42d89.png)

How much each method was off by
![image](https://cloud.githubusercontent.com/assets/5545461/6858324/35b1b710-d3d3-11e4-8ed1-69379eca4f6a.png)

![image](https://cloud.githubusercontent.com/assets/5545461/6858327/387fe08e-d3d3-11e4-8de6-3971e5bf4efa.png)

3)
![image](https://cloud.githubusercontent.com/assets/5545461/6858330/417f2cee-d3d3-11e4-8415-6632215b4c0a.png)

![image](https://cloud.githubusercontent.com/assets/5545461/6858335/474a212e-d3d3-11e4-9ab8-e0c29fb5f936.png)

How much each method was off by
![image](https://cloud.githubusercontent.com/assets/5545461/6858342/50745044-d3d3-11e4-8d16-72b46301cfb7.png)

![image](https://cloud.githubusercontent.com/assets/5545461/6858347/53d2943a-d3d3-11e4-8891-b77a134b938d.png)

**Comment by LindsayL** [comment]
Based on these 3 samples it appear that Average(Average, Average Drift Combination) is the best.  It provided the best total absolute error 2/3 times, and the time it was not the best it was second best.

Since there is so little data it's really hard to judge because I am sure they all perform quite differently once more data is available.  Average will more or less estimate the same value always, Drift will be more extreme because of using the oldest value for 50% of the prediction, and the combinations will sit somewhere in between. (Probably :D)

I guess I would vote Average(Average, Average Drift Combination) but it is one I've made up so I'm not sure if that is acceptable.  Otherwise it's Average or Drift (or something completely different), but between Average and Drift one of them always produces the worst result.

What do you guys think?

**Comment by StevenGerdes** [comment]
I think it is better you made it up actually. And nice job that looks like a lot of work

**Comment by LindsayL** [comment]
Alright, well, I'll implement it. :)

**Comment by LindsayL** [comment]
I implemented it.  Do we want to limit it to predicting just the next day?  Or next 7 days?  Or month?

I did 2 different 2+ day predictions on some data to show what further than 1 day predictions could look like...
They are very predictable...

First, if I factor in previous day's predictions (and treat them like actual data for those days we just trend towards the average).

Second, if I ignore the previous values predicted and just extrapolate the first day predicted line, we will trend linearly away from the average.  (up or down based on the relative position of the last actual data point relevant to the average)

Here are 2 examples:
![image](https://cloud.githubusercontent.com/assets/5545461/6864203/b00b2a96-d423-11e4-8e8e-0b3a16f7ed93.png)

![image](https://cloud.githubusercontent.com/assets/5545461/6864204/b52c97da-d423-11e4-8dbe-0a6e6f221c41.png)

If we are going to show predictions for further than 1 day, I think the second approach would only be appropriate for at most 3 days, even 3 seems to be pushing it in my opinion.  With the first method I think it might be okay for estimating fairly far into the future.  (Since it is quite likely that a fund will return to it's average value [or at least stay around it] I think)

What do you guys think?  It appears we didn't actually make it requirement that we predict any certain amount of time into the future, just that we predict.  Should we provide prediction beyond 1 day?

**Comment by StevenGerdes** [comment]
3 days looks good. I'm not exactly sure if I can see it right but I almost think it could be 4 days. 

Close with 689125c39f24d4d3020de2e50df1615b64085c94
